version: "3"

services:

  # Documentation https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx-dev.html
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:80
    volumes:
      - ./:/app
    environment:
      PHP_DISPLAY_ERRORS: 1
      ENV WEB_DOCUMENT_ROOT: /app/public/
      ENV WEB_DOCUMENT_INDEX: /app/public/index.php
      #APPLICATION_UID: 501
      #APPLICATION_GID: 501
