version: "3"

services:
  # Documentation https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx-dev.html
  web:
    image: webdevops/php-nginx:7.1
    ports:
      - ${PORT}:80
    volumes:
      - ./:/app
    environment:
      PHP_DISPLAY_ERRORS: 1
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      mysql-data:/var/lib/mysql
    ports:
      3306:3306

  redis:
    command: redis-server --requirepass password
    image: redis:3.2.5-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/var/lib/redis/data

volumes:
  mysql-data:
  redis-data:
